### ISSUE TITLE
Help to debug wireui modal component

### ISSUE THREAD

**Issue by leandroneves-net** [PH7-Jack/livewire-ui#1063]
**Describe the bug**

Modal is "blured".

**To Reproduce**
I wrote a single component to use wireui modal, based on wireui docs:  

<x-button label="Open" x-on:click="$openModal('cardModal')" primary />
 
 <x-modal-card title="Edit Customer" name="cardModal">
     <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
         <x-input label="Name" placeholder="Your full name" />
  
         <x-input label="Phone" placeholder="USA phone" />
  
         <div class="col-span-1 sm:col-span-2">
             <x-input label="Email" placeholder="example@mail.com" />
         </div>
  
         <div
             class="flex items-center justify-center col-span-1 bg-gray-100 shadow-md cursor-pointer sm:col-span-2 dark:bg-secondary-700 rounded-xl h-64">
             <div class="flex flex-col items-center justify-center">
                 <x-icon name="cloud-arrow-up" class="w-16 h-16 text-blue-600 dark:text-teal-600" />
  
                 <p class="text-blue-600 dark:text-teal-600">Click or drop files here</p>
             </div>
         </div>
     </div>
  
     <x-slot name="footer" class="flex justify-between gap-x-4">
         <x-button flat negative label="Delete" x-on:click="close" />
  
         <div class="flex gap-x-4">
             <x-button flat label="Cancel" x-on:click="close" />
  
             <x-button primary label="Save" wire:click="save" />
         </div>
     </x-slot>
 </x-modal-card>

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![Image](https://github.com/user-attachments/assets/f01e7a2b-edb1-42cb-9c5d-a9e9664523bd)

**Dependencies**
 - WireUI Version: 2.4
 - Laravel Version: 12.0
 - "livewire/flux": "^2.1.1"
 - "livewire/volt": "^1.7.0",
 - Alpine.js Version: 3.14.9
 - Livewire Version: 3.6.1
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome and Firefox

**Additional context**
How can I debug or solve this problem?

**Comment by leandroneves-net** [comment]
Github is cutting the example: I'm trying here:

```
<x-button label="Open" x-on:click="$openModal('cardModal')" primary />
 
 <x-modal-card title="Edit Customer" name="cardModal">
     <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
         <x-input label="Name" placeholder="Your full name" />
  
         <x-input label="Phone" placeholder="USA phone" />
  
         <div class="col-span-1 sm:col-span-2">
             <x-input label="Email" placeholder="example@mail.com" />
         </div>
  
         <div
             class="flex items-center justify-center col-span-1 bg-gray-100 shadow-md cursor-pointer sm:col-span-2 dark:bg-secondary-700 rounded-xl h-64">
             <div class="flex flex-col items-center justify-center">
                 <x-icon name="cloud-arrow-up" class="w-16 h-16 text-blue-600 dark:text-teal-600" />
  
                 <p class="text-blue-600 dark:text-teal-600">Click or drop files here</p>
             </div>
         </div>
     </div>
  
     <x-slot name="footer" class="flex justify-between gap-x-4">
         <x-button flat negative label="Delete" x-on:click="close" />
  
         <div class="flex gap-x-4">
             <x-button flat label="Cancel" x-on:click="close" />
  
             <x-button primary label="Save" wire:click="save" />
         </div>
     </x-slot>
 </x-modal-card>
```

**Comment by ph7jack** [comment]
Hi @leandroneves-net , it is now fixed. Please, update to the latest release.
Thanks for reporting it

**Comment by swartjie** [comment]
> Hi [@leandroneves-net](https://github.com/leandroneves-net) , it is now fixed. Please, update to the latest release. Thanks for reporting it

I updated to the current version, But still had the same issue.

I also then changed the require version to "wireui/wireui": "dev-main" and the same issue persists...
What am I missing? Can you maybe advise?
