### ISSUE TITLE
Datepicker sometimes appears without calendar

### ISSUE THREAD

**Issue by 1337erik** [PH7-Jack/livewire-ui#472]
**Describe the bug**
This is a completely sporadic issue that usually happens after a value was chosen and the user tries to re-open the calendar. If I open/close the calendar a few times the calendar will eventually open up with just the top row.

I have a hunch theres some issue with loading the proper day values, however there are no console errors. Sometimes the calendar will load with either a small set of the days and one time even after switching the month the calendar displayed with around 40-50 days total ( couldn't reproduce for screenshot ).. noticed that as i switch months, the days are often greyed out until i select a day and then it "realizes" that this group of days is within the month and should be text-color black

**To Reproduce**
Setup a datetime picker with the same attributes as seen in the screenshot, select a value and open/close over and over again.

**Expected behavior**
The calendar appears with the correct days - and the days at all - consistently

**Screenshots or Videos**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/20347157/188918309-ca9e2781-d5ce-461f-a450-9311cda58610.png">
![image](https://user-images.githubusercontent.com/20347157/188919255-c3c009ff-9c37-46ed-ba0f-6b7a9dae42c4.png)
![image](https://user-images.githubusercontent.com/20347157/188921831-2bef99ad-9259-4a8c-8e25-bd0b175756a1.png)

**Dependencies**
 - WireUI Version: 1.7
 - Laravel Version: 9.2
 - Alpine.js Version: we only explicitly have @alpinejs/collapse at version ^3.10.3 in package.json, im assuming alpine is provided via dependency through wireui
 - Livewire Version:  ^2.10
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 104

**Additional context**

**Comment by 1337erik** [comment]
This is a really inconsistent issue where the calendar appears/disappears when you open/close one to many times with a value selected and toggle across months - anyone else ever see this?

**Comment by nearueng** [comment]
yep I've noticed this too. It's a bit unpredictable.

**Comment by nearueng** [comment]
@1337erik fyi, I've gone with the following workaround for now. It's a custom blade component made using flatpickr, but I made it work with wireui and swapped out all the wireui datepickers.

If you'd like to. use it.

I was using it in both deferred and non-deferred contexts, but this should do the trick. 

You can customize it how you like.

**Usage**
`<x-app.datepicker label="Choose date" placeholder="Starting date" wire:model.defer="startDate"/>`


**datepicker.blade.php**
```blade
@props(['label' => 'Choose date', 'placeholder' => 'Date', 'defer' => true])

<div>
    <div x-data="datepicker(@entangle($attributes->wire('model')))" class="relative">
        @if($defer)
            <x-input wire:model.defer="{{ $attributes->wire('model')->value() }}"
                     label="{{ $label }}"
                     placeholder="{{ $placeholder }}"
                     x-ref="myDatepicker"
                     x-model="value"
                     right-icon="calendar"/>
        @else
            <x-input wire:model="{{ $attributes->wire('model')->value() }}"
                     label="{{ $label }}"
                     placeholder="{{ $placeholder }}"
                     x-ref="myDatepicker"
                     x-model="value"
                     right-icon="calendar"/>
        @endif
    </div>

    @once
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

        <script>
            document.addEventListener('alpine:init', () => {
                Alpine.data('datepicker', (model) => ({
                    value: model,
                    init(){
                        this.pickr = flatpickr(this.$refs.myDatepicker, {
                            minDate: new Date(new Date().getTime() - 24*60*60*1000)
                        });

                        this.$watch('value', function(newValue){
                            this.pickr.setDate(newValue);
                        }.bind(this));
                    },
                    reset(){
                        this.value = null;
                    }
                }))
            })
        </script>
    @endonce
</div>

```

**Comment by 1337erik** [comment]
appreciate the response, sad that the solution is to just not use the wireui calendar... any updates from a dev from this?

**Comment by Tiagospem** [comment]
sometimes this happened to me, but it was an error in the livewire rendering, I added wire:key in the dynamic elements and the problem was solved

**Comment by 1337erik** [comment]
I have a few dynamic elements that are mostly keyed, if not all - are you referring to a particular dynamic element within the calendar component itself? If you're referring to other dynamic elements outside of the calendar then I am happy to report that those are already taken account for

**Comment by nearueng** [comment]
@Tiagospem I had all my elements keyed as well. Still happened from time to time.

**Comment by ph7jack** [comment]
@1337erik could you update the wireui and test again?

**Comment by ph7jack** [comment]
Closing it now. If the problem persists, let me know to reopen
