### ISSUE TITLE
Datetime Picker not update if manually change data text input

### ISSUE THREAD

**Issue by MattiaMarchiorato** [PH7-Jack/livewire-ui#985]
Using Datetime Picker if we manually change the date from the input text, this is not reflected on the model

**To Reproduce**
Change text date using keyboard

**Expected behavior**
Can use also input text or disable it

**Dependencies**
 - WireUI Version: "^2.1"
 - Laravel Version: 10

**Screenshots or Videos**
https://github.com/user-attachments/assets/e4a33c91-be13-4223-9b12-e67c0f988bce

**Comment by MattiaMarchiorato** [comment]
Hello
https://github.com/wireui/wireui/blob/main/src/Components/DatetimePicker/views/picker.blade.php
line 100 readonly is not effective

**Comment by MattiaMarchiorato** [comment]
Maybe :attributes="$input" is not necessary in this component? 

```
 <x-wireui-wrapper::element
        readonly
        autocomplete="off"
        :attributes="$input"
        class="cursor-pointer disabled"
        x-bind:value="display"
        x-show="selectedDates.length === 0"
    />
```

**Comment by MatthewHolmes** [comment]
We're experiencing this issue with v2.4.2. Has there been a fix?

**Comment by ph7jack** [comment]
The issue is now fixed. Will be released in the next days.
Thanks for reporting

**Comment by insulae** [comment]
I've updated to version 2.5.1 and the problem persists. When I change the date in the input field, the calendar doesn't update, and if I save, it still sends the calendar date instead of the input date.
